### ISSUE TITLE
error in loading

### ISSUE THREAD

**Issue by infantryman4life** [jimmyjon711/FactorioExtended-Plus-Machines#13]
12.063 Loading mod FactorioExtended-Plus-Machines 0.4.1 (data.lua)
  12.066 Error ModManager.cpp:1385: Failed to load mod "FactorioExtended-Plus-Machines": __FactorioExtended-Plus-Machines__/data.lua:1: ...oExtended-Plus-Machines__/prototypes/entity/__init__.lua:2: ...xtended-Plus-Machines__/prototypes/entity/centrifuge.lua:30: attempt to index field 'animation' (a nil value)
stack traceback:
	...xtended-Plus-Machines__/prototypes/entity/centrifuge.lua:30: in main chunk
	[C]: in function 'require'
	...oExtended-Plus-Machines__/prototypes/entity/__init__.lua:2: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Machines__/data.lua:1: in main chunk
stack traceback:
	[C]: in function 'require'
	...oExtended-Plus-Machines__/prototypes/entity/__init__.lua:2: in main chunk
	[C]: in function 'require'
	__FactorioExtended-Plus-Machines__/data.lua:1: in main chunk
stack traceback:
	[C]: in function 'require'
	__FactorioExtended-Plus-Machines__/data.lua:1: in main chunk
  12.068 Loading mod core 0.0.0 (data.lua)
  12.238 Checksum for core: 3153998413
  12.313 Error ModManager.cpp:1385: Error in assignID, recipe-category with name 'crafting' does not exist.

**Comment by jimmyjon711** [comment]
Do you have any other mods installed besides FE+?

**Comment by infantryman4life** [comment]
pyanodons, space exploration, some of bobs mods and space x

**Comment by billbo99** [comment]
My guess is one of the other mods has removed the animation property from the vanilla "centrifuge" prototype.  

@infantryman4life Could you provide a copy of your "mod-list.json"

**Comment by billbo99** [comment]
0.18.5 has been released,  the issue with the amination set has been fixed within base game now.

**Comment by infantryman4life** [comment]
will that fix it? or do you still want my mod-list

**Comment by billbo99** [comment]
The version on the mod portal will work with 0.18.5 or better.

**Comment by infantryman4life** [comment]
yup it did. thanks :)
